version: '3'
services: 
  backend:
    build: ./backend/
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
  